name: Robô de Atualizacao Automatica

on:
  schedule:
    # Roda automaticamente a cada 30 minutos de segunda a sexta (horário UTC)
    - cron: '*/30 * * * 1-5'
  workflow_dispatch: # Permite disparar manualmente clicando no botão no GitHub

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Concede permissão para o robô salvar alterações no repositório

    steps:
      - name: Baixar arquivos do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas Pandas e Requests
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Executar o Atualizador.py
        run: python Atualizador.py

      - name: Publicar dados_tu.js atualizado no site
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "bot@github.com"
          git add dados_tu.js
          git diff-index --quiet HEAD || git commit -m "🤖 [AUTO-SYNC] Atualizando dados do portal"
          git push
